# Generated by Django 5.0.6 on 2026-06-08 17:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True)),
                ('username', models.CharField(blank=True, default='', max_length=64)),
                ('first_name', models.CharField(blank=True, default='', max_length=128)),
                ('bio', models.TextField(blank=True, default='')),
                ('reason_text', models.CharField(blank=True, default='', max_length=255)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spammer_id', models.BigIntegerField(blank=True, null=True)),
                ('spammer_username', models.CharField(blank=True, default='', max_length=64)),
                ('action_taken', models.CharField(choices=[('deleted', 'Message deleted'), ('banned', 'User banned'), ('deleted_banned', 'Deleted + Banned'), ('flagged', 'Flagged (AI)')], max_length=24)),
                ('stage', models.CharField(blank=True, default='', max_length=32)),
                ('detail', models.CharField(blank=True, default='', max_length=512)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SpamContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('text', 'Text'), ('gif', 'GIF'), ('photo', 'Photo')], max_length=8)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('raw_data', models.TextField(blank=True, default='', help_text='Original text, or a short descriptor for media.')),
                ('hits', models.PositiveIntegerField(default=0)),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField()),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('invite_link', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='UserBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_string', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('username', models.CharField(blank=True, default='', max_length=64)),
                ('telegram_id', models.BigIntegerField(blank=True, null=True)),
                ('api_id', models.IntegerField(blank=True, null=True)),
                ('api_hash', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disconnected', 'Disconnected'), ('connecting', 'Connecting')], default='connecting', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='spamcontent',
            constraint=models.UniqueConstraint(fields=('content_type', 'content_hash'), name='unique_content_fingerprint'),
        ),
        migrations.AddField(
            model_name='securitylog',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='agents.telegramgroup'),
        ),
        migrations.AddField(
            model_name='telegramgroup',
            name='monitored_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='agents.userbot'),
        ),
        migrations.AddField(
            model_name='securitylog',
            name='handled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='agents.userbot'),
        ),
        migrations.AddConstraint(
            model_name='telegramgroup',
            constraint=models.UniqueConstraint(fields=('chat_id', 'monitored_by'), name='unique_group_per_bot'),
        ),
    ]
