# Generated by Django 5.0.6 on 2026-06-08 17:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('keyword', 'Keyword (substring)'), ('emoji', 'Emoji'), ('regex', 'Regex pattern')], max_length=16)),
                ('pattern', models.CharField(max_length=255)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('hits', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['rule_type', 'pattern'],
            },
        ),
        migrations.CreateModel(
            name='PropagationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField()),
                ('admin_title', models.CharField(blank=True, default='Anti-Spam Agent', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('result', models.CharField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='filterrule',
            constraint=models.UniqueConstraint(fields=('rule_type', 'pattern'), name='unique_filter_rule'),
        ),
        migrations.AddField(
            model_name='propagationjob',
            name='admin_bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propagation_jobs_as_admin', to='agents.userbot'),
        ),
        migrations.AddField(
            model_name='propagationjob',
            name='new_bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propagation_jobs_as_target', to='agents.userbot'),
        ),
    ]
