# Generated by Django 5.0.6 on 2026-06-08 18:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_seed_filter_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(db_index=True)),
                ('message_id', models.BigIntegerField()),
                ('sender_id', models.BigIntegerField(blank=True, null=True)),
                ('sender_name', models.CharField(blank=True, default='', max_length=128)),
                ('sender_username', models.CharField(blank=True, default='', max_length=64)),
                ('text', models.TextField(blank=True, default='')),
                ('media_type', models.CharField(blank=True, default='', max_length=24)),
                ('outgoing', models.BooleanField(default=False)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('userbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cached_messages', to='agents.userbot')),
            ],
            options={
                'ordering': ['date', 'message_id'],
            },
        ),
        migrations.CreateModel(
            name='EngineCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('sync_dialogs', 'Sync chat list'), ('fetch_history', 'Fetch chat history')], max_length=20)),
                ('chat_id', models.BigIntegerField(blank=True, null=True)),
                ('limit', models.IntegerField(default=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('result', models.CharField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('userbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='agents.userbot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramDialog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField()),
                ('dialog_type', models.CharField(choices=[('private', 'User'), ('bot', 'Bot'), ('group', 'Group'), ('supergroup', 'Supergroup'), ('channel', 'Channel')], max_length=12)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('username', models.CharField(blank=True, default='', max_length=64)),
                ('is_admin', models.BooleanField(default=False)),
                ('members_count', models.IntegerField(blank=True, null=True)),
                ('monitored', models.BooleanField(default=False)),
                ('last_message', models.CharField(blank=True, default='', max_length=512)),
                ('last_message_date', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('userbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogs', to='agents.userbot')),
            ],
            options={
                'ordering': ['-last_message_date', 'title'],
            },
        ),
        migrations.AddConstraint(
            model_name='chatmessage',
            constraint=models.UniqueConstraint(fields=('userbot', 'chat_id', 'message_id'), name='unique_cached_message'),
        ),
        migrations.AddConstraint(
            model_name='telegramdialog',
            constraint=models.UniqueConstraint(fields=('userbot', 'chat_id'), name='unique_dialog_per_bot'),
        ),
    ]
