# Generated by Django 5.0.6 on 2026-06-08 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_chatmessage_enginecommand_telegramdialog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitylog',
            name='message_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegramgroup',
            name='helper_bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='helper_for_groups', to='agents.userbot'),
        ),
        migrations.AddField(
            model_name='telegramgroup',
            name='monitor_is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='action_taken',
            field=models.CharField(choices=[('deleted', 'Message deleted'), ('banned', 'User banned'), ('deleted_banned', 'Deleted + Banned'), ('flagged', 'Flagged (AI)'), ('reported', 'Reported to helper account')], max_length=24),
        ),
        migrations.CreateModel(
            name='GroupMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(db_index=True)),
                ('message_id', models.BigIntegerField()),
                ('sender_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('sender_name', models.CharField(blank=True, default='', max_length=128)),
                ('sender_username', models.CharField(blank=True, default='', max_length=64)),
                ('sender_role', models.CharField(choices=[('me', 'Me (this account)'), ('admin', 'Group admin'), ('bot', 'Bot'), ('scam', 'Scam / spam'), ('user', 'Regular user')], default='user', max_length=8)),
                ('tg_scam_flag', models.BooleanField(default=False)),
                ('text', models.TextField(blank=True, default='')),
                ('media_type', models.CharField(blank=True, default='', max_length=24)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='agents.telegramgroup')),
                ('userbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_messages', to='agents.userbot')),
            ],
            options={
                'ordering': ['-date', '-message_id'],
                'indexes': [models.Index(fields=['chat_id', 'message_id'], name='agents_grou_chat_id_7ded6e_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='groupmessage',
            constraint=models.UniqueConstraint(fields=('userbot', 'chat_id', 'message_id'), name='unique_archived_group_message'),
        ),
    ]
