# Generated by Django 5.0.6 on 2026-06-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0004_chatmessage_enginecommand_telegramdialog_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filterrule",
            name="rule_type",
            field=models.CharField(
                choices=[
                    ("keyword", "Keyword (substring)"),
                    ("phrase", "Phrase (full text match)"),
                    ("emoji", "Emoji"),
                    ("regex", "Regex pattern"),
                ],
                max_length=16,
            ),
        ),
    ]
