# Generated by Django 5.0.6 on 2026-06-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_securitylog_message_id_telegramgroup_helper_bot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filterrule',
            name='rule_type',
            field=models.CharField(choices=[('keyword', 'Keyword (substring)'), ('phrase', 'Phrase (full text match)'), ('emoji', 'Emoji'), ('regex', 'Regex pattern')], max_length=16),
        ),
    ]
