# Generated by Django 5.0.6

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_alter_filterrule_rule_type'),
    ]

    operations = [
        # --- New model: SpamStrike (3-strike tracking) ---
        migrations.CreateModel(
            name='SpamStrike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('username', models.CharField(blank=True, default='', max_length=64)),
                ('first_name', models.CharField(blank=True, default='', max_length=128)),
                ('strike_count', models.PositiveIntegerField(default=0)),
                ('last_strike_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_banned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='strikes',
                    to='agents.telegramgroup',
                )),
            ],
            options={
                'ordering': ['-last_strike_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='spamstrike',
            constraint=models.UniqueConstraint(
                fields=['group', 'user_id'],
                name='unique_strike_per_user_per_group',
            ),
        ),

        # --- New model: JoinEvent (new member join log) ---
        migrations.CreateModel(
            name='JoinEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('username', models.CharField(blank=True, default='', max_length=64)),
                ('first_name', models.CharField(blank=True, default='', max_length=128)),
                ('bio', models.TextField(blank=True, default='')),
                ('scan_result', models.CharField(
                    choices=[
                        ('clean', 'Clean'),
                        ('nsfw_photo', 'NSFW profile photo'),
                        ('nsfw_channel', 'NSFW linked channel'),
                        ('nsfw_both', 'NSFW photo + channel'),
                        ('scan_failed', 'Scan failed'),
                    ],
                    default='clean',
                    max_length=16,
                )),
                ('action_taken', models.CharField(
                    choices=[
                        ('allowed', 'Allowed'),
                        ('banned', 'Banned + Removed'),
                        ('monitoring', 'Under monitoring'),
                    ],
                    default='allowed',
                    max_length=16,
                )),
                ('detail', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('group', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='join_events',
                    to='agents.telegramgroup',
                )),
                ('userbot', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='join_events',
                    to='agents.userbot',
                )),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),

        # --- Update SecurityLog action choices ---
        migrations.AlterField(
            model_name='securitylog',
            name='action_taken',
            field=models.CharField(
                choices=[
                    ('deleted', 'Message deleted'),
                    ('banned', 'User banned'),
                    ('deleted_banned', 'Deleted + Banned'),
                    ('flagged', 'Flagged (AI)'),
                    ('reported', 'Reported to helper account'),
                    ('join_banned', 'Banned on join (NSFW profile)'),
                    ('join_allowed', 'Allowed on join (clean)'),
                    ('strike_warn', 'Strike warning (msg deleted)'),
                    ('strike_ban', 'Banned after 3 strikes'),
                ],
                max_length=24,
            ),
        ),
    ]
